//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 


//********************************************************************************
//NAME         : CoachFaresService.cs
//AUTHOR       : Murat Guney
//DATE CREATED : 05/10/2005
//DESCRIPTION  : Implementation of CoachFaresService web service class
//				 The additional class definitions are omitted as they already exist in the namespace. See the bottom.
//				 When this file needs to be regenerated using wsdl, the same aproach should be taken.
//				 This is because the WSDL file is created by TD not the providers. 
//********************************************************************************
//$Log:   P:/TDPortal/archives/DotNet2.0Codebase/TransportDirect/PricingRetail/CoachFareInterfaces/CoachFaresService.cs-arc  $
//
//   Rev 1.0   Nov 08 2007 12:36:28   mturner
//Initial revision.
//
//   Rev 1.2   Oct 13 2005 14:53:02   mguney
//Creation date corrected.
//Resolution for 2818: DEL 7.3 Stream: Search by Price
//
//   Rev 1.1   Oct 12 2005 11:03:18   mguney
//Initial draft Associated SCR
//Resolution for 2818: DEL 7.3 Stream: Search by Price
//
//   Rev 1.0   Oct 12 2005 11:00:36   mguney
//Initial revision.


using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;

namespace TransportDirect.UserPortal.PricingRetail.CoachFareInterfaces
{
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="CoachFaresServiceSoap", Namespace="http://www.transportdirect.info")]
	public class CoachFaresService : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
	    
		/// <remarks/>
		public CoachFaresService() 
		{
			this.Url = "http://localhost/CoachFaresWebService/CoachFaresService.asmx";
		}
	    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportdirect.info/GetCoachFares", RequestNamespace="http://www.transportdirect.info", ResponseNamespace="http://www.transportdirect.info", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public FareResultRemote GetCoachFares(string requestId, string originNaPTAN, string destinationNaPTAN, System.DateTime outwardStartDateTime, System.DateTime outwardEndDateTime, System.DateTime returnStartDateTime, System.DateTime returnEndDateTime) 
		{
			object[] results = this.Invoke("GetCoachFares", new object[] {
																			 requestId,
																			 originNaPTAN,
																			 destinationNaPTAN,
																			 outwardStartDateTime,
																			 outwardEndDateTime,
																			 returnStartDateTime,
																			 returnEndDateTime});
			return ((FareResultRemote)(results[0]));
		}
	    
		/// <remarks/>
		public System.IAsyncResult BeginGetCoachFares(string requestId, string originNaPTAN, string destinationNaPTAN, System.DateTime outwardStartDateTime, System.DateTime outwardEndDateTime, System.DateTime returnStartDateTime, System.DateTime returnEndDateTime, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("GetCoachFares", new object[] {
																	  requestId,
																	  originNaPTAN,
																	  destinationNaPTAN,
																	  outwardStartDateTime,
																	  outwardEndDateTime,
																	  returnStartDateTime,
																	  returnEndDateTime}, callback, asyncState);
		}
	    
		/// <remarks/>
		public FareResultRemote EndGetCoachFares(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((FareResultRemote)(results[0]));
		}
	}

	/*
	*****************THE FOLLOWING CLASS DEFINITIONS ARE OMITTED AS THEY ALREADY EXIST IN THE NAMESPACE*********************

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info")]
	public class FareResultRemote 
	{
	    
		/// <remarks/>
		public CoachFareRemoteForRoute[] Fares;
	    
		/// <remarks/>
		public int[] ErrorCodeList;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info")]
	public class CoachFareRemoteForRoute 
	{
	    
		/// <remarks/>
		public string OriginNaPTAN;
	    
		/// <remarks/>
		public string DestinationNaPTAN;
	    
		/// <remarks/>
		public System.DateTime FareStartDate;
	    
		/// <remarks/>
		public System.DateTime FareEndDate;
	    
		/// <remarks/>
		public DayRestriction DayRestriction;
	    
		/// <remarks/>
		public FlexibilityType Flexibility;
	    
		/// <remarks/>
		public string[] ChangeNaPTANs;
	    
		/// <remarks/>
		public TimeRestriction[] TimeRestrictions;
	    
		/// <remarks/>
		public string[] RestrictedServices;
	    
		/// <remarks/>
		public int AdvancePurchaseDays;
	    
		/// <remarks/>
		public bool IsDayReturn;
	    
		/// <remarks/>
		public AvailabilityScore Availability;
	    
		/// <remarks/>
		public string RestrictedOperatorCodes;
	    
		/// <remarks/>
		public bool IsAdult;
	    
		/// <remarks/>
		public bool IsSingle;
	    
		/// <remarks/>
		public int Fare;
	    
		/// <remarks/>
		public string PassengerType;
	    
		/// <remarks/>
		public string PassengerTypeConditions;
	    
		/// <remarks/>
		public string DiscountCardType;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info")]
	public enum DayRestriction 
	{
	    
		/// <remarks/>
		Monday,
	    
		/// <remarks/>
		Tuesday,
	    
		/// <remarks/>
		Wednesday,
	    
		/// <remarks/>
		Thursday,
	    
		/// <remarks/>
		Friday,
	    
		/// <remarks/>
		Saturday,
	    
		/// <remarks/>
		Sunday,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info")]
	public enum FlexibilityType 
	{
	    
		/// <remarks/>
		Low,
	    
		/// <remarks/>
		Fully,
	    
		/// <remarks/>
		No,
	    
		/// <remarks/>
		Unknown,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info")]
	public class TimeRestriction 
	{
	    
		/// <remarks/>
		public System.DateTime StartTime;
	    
		/// <remarks/>
		public System.DateTime EndTime;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info")]
	public enum AvailabilityScore 
	{
	    
		/// <remarks/>
		Low,
	    
		/// <remarks/>
		Medium,
	    
		/// <remarks/>
		High,
	}
	*/
}