CREATE TABLE [dbo].[TravelNewsSeverity]
(
	[SeverityID] [tinyint] NOT NULL,
	[SeverityDescription] [varchar](15) NOT NULL,
 CONSTRAINT [PK_TravelNewsSeverity] PRIMARY KEY CLUSTERED 
(
	[SeverityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_TravelNewsSeverity] UNIQUE NONCLUSTERED 
(
	[SeverityDescription] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
