CREATE TABLE [dbo].[properties](
	[pName] [varchar](255) NOT NULL,
	[pValue] [varchar](2000) NOT NULL,
	[AID] [varchar](50) NOT NULL,
	[GID] [varchar](50) NOT NULL
 CONSTRAINT [PK_Properties] PRIMARY KEY CLUSTERED 
(
	[pName] ASC,
	[AID] ASC,
	[GID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]