//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportDirect.UserPortal.Web.Templates {
    
    
    /// <summary>
    /// FindFareDateSelection class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class FindFareDateSelection {
        
        /// <summary>
        /// headElementControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.HeadElementControl headElementControl;
        
        /// <summary>
        /// expandableMenuControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.ExpandableMenuControl expandableMenuControl;
        
        /// <summary>
        /// mainbit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.RoundedCornerControl mainbit;
        
        /// <summary>
        /// theJourneysSearchedForControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.JourneysSearchedForControl theJourneysSearchedForControl1;
        
        /// <summary>
        /// findFareStepsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.FindFareStepsControl findFareStepsControl;
        
        /// <summary>
        /// helpLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.HelpLabelControl helpLabel;
        
        /// <summary>
        /// JourneyPlannerOutputTitleControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.JourneyPlannerOutputTitle JourneyPlannerOutputTitleControl1;
        
        /// <summary>
        /// instructionPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel instructionPanel;
        
        /// <summary>
        /// instructionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label instructionLabel;
        
        /// <summary>
        /// errorMessagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel errorMessagePanel;
        
        /// <summary>
        /// errorMessageLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label errorMessageLabel;
        
        /// <summary>
        /// noteLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label noteLabel;
        
        /// <summary>
        /// buttonDateSelectionSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.TDButton buttonDateSelectionSubmit;
        
        /// <summary>
        /// FooterControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TransportDirect.UserPortal.Web.Controls.FooterControl FooterControl1;
    }
}
