//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
// 
namespace TransportDirect.EnhancedExposedServices.TaxiInformation.V1.Test 
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="TaxiInformationServiceSoap", Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1")]
	public class TestTaxiInformationServiceWse : Microsoft.Web.Services3.WebServicesClientProtocol 
	{
        
		/// <remarks/>
		public TestTaxiInformationServiceWse() 
		{
			this.Url = "http://localhost/EnhancedExposedServices/TaxiInformation/v1/TaxiInformationservic" +
				"e.asmx";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1/GetTaxiInfo", RequestNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1", ResponseNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public TaxiInformationStopDetail GetTaxiInfo(string transactionId, string language, string naptanId) 
		{
			object[] results = this.Invoke("GetTaxiInfo", new object[] {
																		   transactionId,
																		   language,
																		   naptanId});
			return ((TaxiInformationStopDetail)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginGetTaxiInfo(string transactionId, string language, string naptanId, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("GetTaxiInfo", new object[] {
																	transactionId,
																	language,
																	naptanId}, callback, asyncState);
		}
        
		/// <remarks/>
		public TaxiInformationStopDetail EndGetTaxiInfo(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((TaxiInformationStopDetail)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="TaxiInformationServiceSoap", Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1")]
	public class TaxiInformationService : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		/// <remarks/>
		public TaxiInformationService() 
		{
			this.Url = "http://localhost/EnhancedExposedServices/TaxiInformation/v1/TaxiInformationservic" +
				"e.asmx";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1/GetTaxiInfo", RequestNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1", ResponseNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public TaxiInformationStopDetail GetTaxiInfo(string transactionId, string language, string naptanId) 
		{
			object[] results = this.Invoke("GetTaxiInfo", new object[] {
																		   transactionId,
																		   language,
																		   naptanId});
			return ((TaxiInformationStopDetail)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginGetTaxiInfo(string transactionId, string language, string naptanId, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("GetTaxiInfo", new object[] {
																	transactionId,
																	language,
																	naptanId}, callback, asyncState);
		}
        
		/// <remarks/>
		public TaxiInformationStopDetail EndGetTaxiInfo(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((TaxiInformationStopDetail)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1")]
	public class TaxiInformationStopDetail 
	{
        
		/// <remarks/>
		public string StopName;
        
		/// <remarks/>
		public string StopNaptan;
        
		/// <remarks/>
		public string Comment;
        
		/// <remarks/>
		public TaxiInformationOperator[] Operators;
        
		/// <remarks/>
		public TaxiInformationStopDetail[] AlternativeStops;
        
		/// <remarks/>
		public bool AccessibleOperatorPresent;
        
		/// <remarks/>
		public string AccessibleText;
        
		/// <remarks/>
		public bool InformationAvailable;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.TaxiInformation.V1")]
	public class TaxiInformationOperator 
	{
        
		/// <remarks/>
		public string Name;
        
		/// <remarks/>
		public string PhoneNumber;
        
		/// <remarks/>
		public bool Accessible;
	}
}
