USE [master]
GO

/****** Object:  Database [BatchJourneyPlanner]    Script Date: 01/12/2012 15:14:25 ******/
CREATE DATABASE [BatchJourneyPlanner] ON  PRIMARY 
( NAME = N'BatchJourneyPlanner', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\BatchJourneyPlanner.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BatchJourneyPlanner_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\BatchJourneyPlanner_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE SQL_Latin1_General_CP1_CI_AS
GO

ALTER DATABASE [BatchJourneyPlanner] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BatchJourneyPlanner].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BatchJourneyPlanner] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET ARITHABORT OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BatchJourneyPlanner] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BatchJourneyPlanner] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BatchJourneyPlanner] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BatchJourneyPlanner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BatchJourneyPlanner] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BatchJourneyPlanner] SET  READ_WRITE 
GO

ALTER DATABASE [BatchJourneyPlanner] SET RECOVERY FULL 
GO

ALTER DATABASE [BatchJourneyPlanner] SET  MULTI_USER 
GO

ALTER DATABASE [BatchJourneyPlanner] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BatchJourneyPlanner] SET DB_CHAINING OFF 
GO


