ALTER TABLE [dbo].[SJPZoneAreaPoints]
	ADD CONSTRAINT [PK_SJPZoneAreaPoints]
	PRIMARY KEY CLUSTERED
	(
		[ZoneAreaID],
		[Easting],
		[Northing]
	) 
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]