
ALTER TABLE [dbo].[StopAccessibilityLinks] ADD  CONSTRAINT [PK_StopAccessibilityLinks] PRIMARY KEY CLUSTERED 
(
	[StopNaPTAN] ASC,
	[StopOperator] ASC,
	[LinkUrl] ASC,
	[WEFDate] ASC,
	[WEUDate] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

