ALTER AUTHORIZATION ON DATABASE::AirInterchange TO sa
ALTER AUTHORIZATION ON DATABASE::CP_Routing TO sa
ALTER AUTHORIZATION ON DATABASE::NPTG TO sa
ALTER AUTHORIZATION ON DATABASE::Routing TO sa
ALTER AUTHORIZATION ON DATABASE::SJPConfiguration TO sa
ALTER AUTHORIZATION ON DATABASE::SJPContent TO sa
ALTER AUTHORIZATION ON DATABASE::SJPGazetteer TO sa
ALTER AUTHORIZATION ON DATABASE::SJPTransientPortal TO sa