CREATE TABLE [dbo].[ChangeNotification]
(
	[Version] [int] NOT NULL,
	[Table] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ChangeNotification] PRIMARY KEY CLUSTERED 
(
	[Table] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]