//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.UserPortal.CyclePlannerService.CyclePlannerWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface", ConfigurationName="CyclePlannerWebService.CyclePlannerServiceSoap")]
    public interface CyclePlannerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface/JourneyPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerResult JourneyPlan(TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JourneyRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public abstract partial class CyclePlannerRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool referenceTransactionField;
        
        private string requestIDField;
        
        private string languageField;
        
        private string sessionIDField;
        
        private int userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool referenceTransaction {
            get {
                return this.referenceTransactionField;
            }
            set {
                this.referenceTransactionField = value;
                this.RaisePropertyChanged("referenceTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("userType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class CycleRoute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class ITNLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tOIDField;
        
        private int congestionField;
        
        private string geometryField;
        
        private bool interpolateGradientField;
        
        private string styleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TOID {
            get {
                return this.tOIDField;
            }
            set {
                this.tOIDField = value;
                this.RaisePropertyChanged("TOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int congestion {
            get {
                return this.congestionField;
            }
            set {
                this.congestionField = value;
                this.RaisePropertyChanged("congestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
                this.RaisePropertyChanged("geometry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool interpolateGradient {
            get {
                return this.interpolateGradientField;
            }
            set {
                this.interpolateGradientField = value;
                this.RaisePropertyChanged("interpolateGradient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
                this.RaisePropertyChanged("style");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointOnITNLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ITNNode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class StopoverPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tOIDField;
        
        private string geometryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TOID {
            get {
                return this.tOIDField;
            }
            set {
                this.tOIDField = value;
                this.RaisePropertyChanged("TOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
                this.RaisePropertyChanged("geometry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class PointOnITNLink : StopoverPoint {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class ITNNode : StopoverPoint {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSectionFeature))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionFeatureAttributes))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public abstract partial class SectionFeature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class TextSectionFeature : SectionFeature {
        
        private FeatureType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FeatureType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public enum FeatureType {
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        URL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class SectionFeatureAttributes : SectionFeature {
        
        private uint valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DriveSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JunctionDriveSection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StopoverSection))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public abstract partial class Section : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sectionIDField;
        
        private System.DateTime timeField;
        
        private uint[] nodeAttributesField;
        
        private SectionFeature[] sectionFeaturesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int sectionID {
            get {
                return this.sectionIDField;
            }
            set {
                this.sectionIDField = value;
                this.RaisePropertyChanged("sectionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public uint[] nodeAttributes {
            get {
                return this.nodeAttributesField;
            }
            set {
                this.nodeAttributesField = value;
                this.RaisePropertyChanged("nodeAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public SectionFeature[] sectionFeatures {
            get {
                return this.sectionFeaturesField;
            }
            set {
                this.sectionFeaturesField = value;
                this.RaisePropertyChanged("sectionFeatures");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JunctionDriveSection))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class DriveSection : Section {
        
        private string nameField;
        
        private string numberField;
        
        private int distanceField;
        
        private int turnCountField;
        
        private TurnDirection turnDirectionField;
        
        private TurnAngle turnAngleField;
        
        private int costField;
        
        private string headingField;
        
        private bool roadSplitsField;
        
        private uint[] joiningSignificantLinkAttributesField;
        
        private uint[] leavingSignificantLinkAttributesField;
        
        private uint[] interestingLinkAttributesField;
        
        private uint[] significantNodeAttributesField;
        
        private string instructionTextField;
        
        private ITNLink[] linksField;
        
        private CycleRoute[] cycleRoutesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int turnCount {
            get {
                return this.turnCountField;
            }
            set {
                this.turnCountField = value;
                this.RaisePropertyChanged("turnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TurnDirection turnDirection {
            get {
                return this.turnDirectionField;
            }
            set {
                this.turnDirectionField = value;
                this.RaisePropertyChanged("turnDirection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TurnAngle turnAngle {
            get {
                return this.turnAngleField;
            }
            set {
                this.turnAngleField = value;
                this.RaisePropertyChanged("turnAngle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
                this.RaisePropertyChanged("heading");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool roadSplits {
            get {
                return this.roadSplitsField;
            }
            set {
                this.roadSplitsField = value;
                this.RaisePropertyChanged("roadSplits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public uint[] joiningSignificantLinkAttributes {
            get {
                return this.joiningSignificantLinkAttributesField;
            }
            set {
                this.joiningSignificantLinkAttributesField = value;
                this.RaisePropertyChanged("joiningSignificantLinkAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public uint[] leavingSignificantLinkAttributes {
            get {
                return this.leavingSignificantLinkAttributesField;
            }
            set {
                this.leavingSignificantLinkAttributesField = value;
                this.RaisePropertyChanged("leavingSignificantLinkAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public uint[] interestingLinkAttributes {
            get {
                return this.interestingLinkAttributesField;
            }
            set {
                this.interestingLinkAttributesField = value;
                this.RaisePropertyChanged("interestingLinkAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public uint[] significantNodeAttributes {
            get {
                return this.significantNodeAttributesField;
            }
            set {
                this.significantNodeAttributesField = value;
                this.RaisePropertyChanged("significantNodeAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string instructionText {
            get {
                return this.instructionTextField;
            }
            set {
                this.instructionTextField = value;
                this.RaisePropertyChanged("instructionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public ITNLink[] links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
                this.RaisePropertyChanged("links");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public CycleRoute[] cycleRoutes {
            get {
                return this.cycleRoutesField;
            }
            set {
                this.cycleRoutesField = value;
                this.RaisePropertyChanged("cycleRoutes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public enum TurnDirection {
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Right,
        
        /// <remarks/>
        Continue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public enum TurnAngle {
        
        /// <remarks/>
        Turn,
        
        /// <remarks/>
        Bear,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        Return,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class JunctionDriveSection : DriveSection {
        
        private string junctionNumberField;
        
        private JunctionType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string junctionNumber {
            get {
                return this.junctionNumberField;
            }
            set {
                this.junctionNumberField = value;
                this.RaisePropertyChanged("junctionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public JunctionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public enum JunctionType {
        
        /// <remarks/>
        Entry,
        
        /// <remarks/>
        Exit,
        
        /// <remarks/>
        Merge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class StopoverSection : Section {
        
        private StopoverSectionType typeField;
        
        private string nameField;
        
        private int tollField;
        
        private StopoverPoint nodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StopoverSectionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int toll {
            get {
                return this.tollField;
            }
            set {
                this.tollField = value;
                this.RaisePropertyChanged("toll");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StopoverPoint node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
                this.RaisePropertyChanged("node");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public enum StopoverSectionType {
        
        /// <remarks/>
        Origin,
        
        /// <remarks/>
        Destination,
        
        /// <remarks/>
        Via,
        
        /// <remarks/>
        Wait,
        
        /// <remarks/>
        UndefinedWait,
        
        /// <remarks/>
        Toll,
        
        /// <remarks/>
        TollEntry,
        
        /// <remarks/>
        TollExit,
        
        /// <remarks/>
        CongestionZoneEntry,
        
        /// <remarks/>
        CongestionZoneExit,
        
        /// <remarks/>
        CongestionZoneEnd,
        
        /// <remarks/>
        FerryCheckIn,
        
        /// <remarks/>
        FerryCheckOut,
        
        /// <remarks/>
        NamedAccessRestriction,
        
        /// <remarks/>
        ComplexManoeuvre,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class Journey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startTimeField;
        
        private Section[] sectionsField;
        
        private StopoverSection startField;
        
        private StopoverSection finishField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Section[] sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
                this.RaisePropertyChanged("sections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StopoverSection start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StopoverSection finish {
            get {
                return this.finishField;
            }
            set {
                this.finishField = value;
                this.RaisePropertyChanged("finish");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JourneyResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class CyclePlannerResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Message[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Message[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class JourneyResult : CyclePlannerResult {
        
        private Journey[] journeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Journey[] journeys {
            get {
                return this.journeysField;
            }
            set {
                this.journeysField = value;
                this.RaisePropertyChanged("journeys");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class UserPreference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int parameterIDField;
        
        private string parameterValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int parameterID {
            get {
                return this.parameterIDField;
            }
            set {
                this.parameterIDField = value;
                this.RaisePropertyChanged("parameterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string parameterValue {
            get {
                return this.parameterValueField;
            }
            set {
                this.parameterValueField = value;
                this.RaisePropertyChanged("parameterValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class JourneyResultSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool includeToidsField;
        
        private bool includeGeometryField;
        
        private bool includeTextField;
        
        private char pointSeparatorField;
        
        private char eastingNorthingSeparatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool includeToids {
            get {
                return this.includeToidsField;
            }
            set {
                this.includeToidsField = value;
                this.RaisePropertyChanged("includeToids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool includeGeometry {
            get {
                return this.includeGeometryField;
            }
            set {
                this.includeGeometryField = value;
                this.RaisePropertyChanged("includeGeometry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool includeText {
            get {
                return this.includeTextField;
            }
            set {
                this.includeTextField = value;
                this.RaisePropertyChanged("includeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public char pointSeparator {
            get {
                return this.pointSeparatorField;
            }
            set {
                this.pointSeparatorField = value;
                this.RaisePropertyChanged("pointSeparator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public char eastingNorthingSeparator {
            get {
                return this.eastingNorthingSeparatorField;
            }
            set {
                this.eastingNorthingSeparatorField = value;
                this.RaisePropertyChanged("eastingNorthingSeparator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class Coordinate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eastingField;
        
        private int northingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int easting {
            get {
                return this.eastingField;
            }
            set {
                this.eastingField = value;
                this.RaisePropertyChanged("easting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int northing {
            get {
                return this.northingField;
            }
            set {
                this.northingField = value;
                this.RaisePropertyChanged("northing");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class Seed : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int distanceFromANodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int distanceFromANode {
            get {
                return this.distanceFromANodeField;
            }
            set {
                this.distanceFromANodeField = value;
                this.RaisePropertyChanged("distanceFromANode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class ITN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tOIDField;
        
        private System.DateTime timeDateField;
        
        private bool nodeField;
        
        private Seed seedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TOID {
            get {
                return this.tOIDField;
            }
            set {
                this.tOIDField = value;
                this.RaisePropertyChanged("TOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timeDate {
            get {
                return this.timeDateField;
            }
            set {
                this.timeDateField = value;
                this.RaisePropertyChanged("timeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
                this.RaisePropertyChanged("node");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Seed seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
                this.RaisePropertyChanged("seed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class RequestPlace : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string givenNameField;
        
        private System.DateTime timeDateField;
        
        private ITN[] roadPointsField;
        
        private Coordinate coordinateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
                this.RaisePropertyChanged("givenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timeDate {
            get {
                return this.timeDateField;
            }
            set {
                this.timeDateField = value;
                this.RaisePropertyChanged("timeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ITN[] roadPoints {
            get {
                return this.roadPointsField;
            }
            set {
                this.roadPointsField = value;
                this.RaisePropertyChanged("roadPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Coordinate coordinate {
            get {
                return this.coordinateField;
            }
            set {
                this.coordinateField = value;
                this.RaisePropertyChanged("coordinate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.208")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.atkinsglobal.com/journeyplanning/cycleplannerinterface")]
    public partial class JourneyRequest : CyclePlannerRequest {
        
        private bool departField;
        
        private string penaltyFunctionField;
        
        private RequestPlace originField;
        
        private RequestPlace destinationField;
        
        private JourneyResultSettings journeyResultSettingsField;
        
        private RequestPlace[] viasField;
        
        private UserPreference[] userPreferencesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool depart {
            get {
                return this.departField;
            }
            set {
                this.departField = value;
                this.RaisePropertyChanged("depart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string penaltyFunction {
            get {
                return this.penaltyFunctionField;
            }
            set {
                this.penaltyFunctionField = value;
                this.RaisePropertyChanged("penaltyFunction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RequestPlace origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RequestPlace destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public JourneyResultSettings journeyResultSettings {
            get {
                return this.journeyResultSettingsField;
            }
            set {
                this.journeyResultSettingsField = value;
                this.RaisePropertyChanged("journeyResultSettings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public RequestPlace[] vias {
            get {
                return this.viasField;
            }
            set {
                this.viasField = value;
                this.RaisePropertyChanged("vias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public UserPreference[] userPreferences {
            get {
                return this.userPreferencesField;
            }
            set {
                this.userPreferencesField = value;
                this.RaisePropertyChanged("userPreferences");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CyclePlannerServiceSoapChannel : TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CyclePlannerServiceSoapClient : System.ServiceModel.ClientBase<TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerServiceSoap>, TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerServiceSoap {
        
        public CyclePlannerServiceSoapClient() {
        }
        
        public CyclePlannerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CyclePlannerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CyclePlannerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CyclePlannerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerResult JourneyPlan(TDP.UserPortal.CyclePlannerService.CyclePlannerWebService.CyclePlannerRequest request) {
            return base.Channel.JourneyPlan(request);
        }
    }
}
