/*ALTER TABLE [dbo].[SJPPierVenueNavigationPath]
    ADD CONSTRAINT [PK_PierVenueNavigationPath] PRIMARY KEY CLUSTERED ([NavigationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

