ALTER TABLE [dbo].[SJPCarParkTransitShuttles]
    ADD CONSTRAINT [PK_SJPCarParkTransitShuttles] 
	PRIMARY KEY CLUSTERED ([TransitShuttleID],[ToVenue],[VenueGateNaPTAN] ASC) 
	WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, 
	STATISTICS_NORECOMPUTE = OFF);

