ALTER TABLE [dbo].[SJPCarParkAvailability]
    ADD CONSTRAINT [PK_SJPCarParkAvailability] PRIMARY KEY CLUSTERED ([AvailabilityID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

