ALTER TABLE [dbo].[TDPVenueAdditionalData]
    ADD CONSTRAINT [PK_TDPVenueAdditionalData] PRIMARY KEY CLUSTERED ([VenueNaPTAN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

