ALTER TABLE [dbo].[SJPCarParksCarParkAvailability]
	ADD CONSTRAINT [PK_SJPCarParksCarParkAvailability]
	PRIMARY KEY CLUSTERED ([CarParkID],[AvailabilityID]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
