ALTER TABLE [dbo].[SJPCarParkTransitShuttleTransfers]
	ADD CONSTRAINT [PK_SJPCarParkTransitShuttleTransfers]
	PRIMARY KEY CLUSTERED ([TransitShuttleID],[CultureCode] ASC) 
	WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, 
	STATISTICS_NORECOMPUTE = OFF);