ALTER TABLE [dbo].[SJPCarParks]
    ADD CONSTRAINT [PK_SJPCarParks] PRIMARY KEY CLUSTERED ([CarParkID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
