ALTER TABLE [dbo].[TDPVenueGateCheckConstraints]
	ADD CONSTRAINT [PK_TDPVenueGateCheckConstraints]
	PRIMARY KEY ([CheckConstraintID]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
