//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace TransportDirect.ReportDataProvider.TransactionWebService.TDP.EES.DepartureBoardService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DepartureBoardServiceSoap", Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDepartureBoardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartureBoardTimeRequestTypesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DepartureBoardService() {
            this.Url = global::TransportDirect.ReportDataProvider.TransactionWebService.Properties.Settings.Default.td_reportdataprovider_transactionwebservice_TDP_EES_DepartureBoardService_DepartureBoardService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDepartureBoardCompletedEventHandler GetDepartureBoardCompleted;
        
        /// <remarks/>
        public event GetDepartureBoardTimeRequestTypesCompletedEventHandler GetDepartureBoardTimeRequestTypesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
            "Board.V1/GetDepartureBoard", RequestNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
            "Board.V1", ResponseNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
            "Board.V1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartureBoardServiceStopInformation[] GetDepartureBoard(string transactionId, string language, DepartureBoardServiceRequest departureBoardRequest) {
            object[] results = this.Invoke("GetDepartureBoard", new object[] {
                        transactionId,
                        language,
                        departureBoardRequest});
            return ((DepartureBoardServiceStopInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartureBoardAsync(string transactionId, string language, DepartureBoardServiceRequest departureBoardRequest) {
            this.GetDepartureBoardAsync(transactionId, language, departureBoardRequest, null);
        }
        
        /// <remarks/>
        public void GetDepartureBoardAsync(string transactionId, string language, DepartureBoardServiceRequest departureBoardRequest, object userState) {
            if ((this.GetDepartureBoardOperationCompleted == null)) {
                this.GetDepartureBoardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartureBoardOperationCompleted);
            }
            this.InvokeAsync("GetDepartureBoard", new object[] {
                        transactionId,
                        language,
                        departureBoardRequest}, this.GetDepartureBoardOperationCompleted, userState);
        }
        
        private void OnGetDepartureBoardOperationCompleted(object arg) {
            if ((this.GetDepartureBoardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartureBoardCompleted(this, new GetDepartureBoardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
            "Board.V1/GetDepartureBoardTimeRequestTypes", RequestNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
            "Board.V1", ResponseNamespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
            "Board.V1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartureBoardServiceTimeRequestType[] GetDepartureBoardTimeRequestTypes(string transactionId, string language) {
            object[] results = this.Invoke("GetDepartureBoardTimeRequestTypes", new object[] {
                        transactionId,
                        language});
            return ((DepartureBoardServiceTimeRequestType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartureBoardTimeRequestTypesAsync(string transactionId, string language) {
            this.GetDepartureBoardTimeRequestTypesAsync(transactionId, language, null);
        }
        
        /// <remarks/>
        public void GetDepartureBoardTimeRequestTypesAsync(string transactionId, string language, object userState) {
            if ((this.GetDepartureBoardTimeRequestTypesOperationCompleted == null)) {
                this.GetDepartureBoardTimeRequestTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartureBoardTimeRequestTypesOperationCompleted);
            }
            this.InvokeAsync("GetDepartureBoardTimeRequestTypes", new object[] {
                        transactionId,
                        language}, this.GetDepartureBoardTimeRequestTypesOperationCompleted, userState);
        }
        
        private void OnGetDepartureBoardTimeRequestTypesOperationCompleted(object arg) {
            if ((this.GetDepartureBoardTimeRequestTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartureBoardTimeRequestTypesCompleted(this, new GetDepartureBoardTimeRequestTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceRequest {
        
        private DepartureBoardServiceLocation originLocationField;
        
        private DepartureBoardServiceLocation destinationLocationField;
        
        private DepartureBoardServiceTimeRequest journeyTimeInformationField;
        
        private DepartureBoardServiceRangeType rangeTypeField;
        
        private int rangeField;
        
        private bool showDeparturesField;
        
        private string serviceNumberField;
        
        private bool showCallingStopsField;
        
        /// <remarks/>
        public DepartureBoardServiceLocation OriginLocation {
            get {
                return this.originLocationField;
            }
            set {
                this.originLocationField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceLocation DestinationLocation {
            get {
                return this.destinationLocationField;
            }
            set {
                this.destinationLocationField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceTimeRequest JourneyTimeInformation {
            get {
                return this.journeyTimeInformationField;
            }
            set {
                this.journeyTimeInformationField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceRangeType RangeType {
            get {
                return this.rangeTypeField;
            }
            set {
                this.rangeTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        public bool ShowDepartures {
            get {
                return this.showDeparturesField;
            }
            set {
                this.showDeparturesField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool ShowCallingStops {
            get {
                return this.showCallingStopsField;
            }
            set {
                this.showCallingStopsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceLocation {
        
        private string[] naptanIdsField;
        
        private string localityField;
        
        private string codeField;
        
        private DepartureBoardServiceCodeType typeField;
        
        private bool validField;
        
        /// <remarks/>
        public string[] NaptanIds {
            get {
                return this.naptanIdsField;
            }
            set {
                this.naptanIdsField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceCodeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceCodeType {
        
        /// <remarks/>
        CRS,
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        IATA,
        
        /// <remarks/>
        Postcode,
        
        /// <remarks/>
        NAPTAN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceItinerary {
        
        private string operatorCodeField;
        
        private string operatorNameField;
        
        private string serviceNumberField;
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceNumber {
            get {
                return this.serviceNumberField;
            }
            set {
                this.serviceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceStop {
        
        private string naptanIdField;
        
        private string nameField;
        
        private string shortCodeField;
        
        /// <remarks/>
        public string NaptanId {
            get {
                return this.naptanIdField;
            }
            set {
                this.naptanIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ShortCode {
            get {
                return this.shortCodeField;
            }
            set {
                this.shortCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartureBoardServiceTrainRealTime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceRealTime {
        
        private System.DateTime departTimeField;
        
        private DepartureBoardServiceRealTimeType departTimeTypeField;
        
        private System.DateTime arriveTimeField;
        
        private DepartureBoardServiceRealTimeType arriveTimeTypeField;
        
        /// <remarks/>
        public System.DateTime DepartTime {
            get {
                return this.departTimeField;
            }
            set {
                this.departTimeField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceRealTimeType DepartTimeType {
            get {
                return this.departTimeTypeField;
            }
            set {
                this.departTimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ArriveTime {
            get {
                return this.arriveTimeField;
            }
            set {
                this.arriveTimeField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceRealTimeType ArriveTimeType {
            get {
                return this.arriveTimeTypeField;
            }
            set {
                this.arriveTimeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceRealTimeType {
        
        /// <remarks/>
        Recorded,
        
        /// <remarks/>
        Estimated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceTrainRealTime : DepartureBoardServiceRealTime {
        
        private bool delayedField;
        
        private bool uncertainField;
        
        /// <remarks/>
        public bool Delayed {
            get {
                return this.delayedField;
            }
            set {
                this.delayedField = value;
            }
        }
        
        /// <remarks/>
        public bool Uncertain {
            get {
                return this.uncertainField;
            }
            set {
                this.uncertainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceInformation {
        
        private DepartureBoardServiceActivityType activityTypeField;
        
        private System.DateTime departTimeField;
        
        private System.DateTime arriveTimeField;
        
        private DepartureBoardServiceRealTime realTimeField;
        
        private DepartureBoardServiceStop stopField;
        
        private bool cancelledField;
        
        /// <remarks/>
        public DepartureBoardServiceActivityType ActivityType {
            get {
                return this.activityTypeField;
            }
            set {
                this.activityTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DepartTime {
            get {
                return this.departTimeField;
            }
            set {
                this.departTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ArriveTime {
            get {
                return this.arriveTimeField;
            }
            set {
                this.arriveTimeField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceRealTime RealTime {
            get {
                return this.realTimeField;
            }
            set {
                this.realTimeField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceStop Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        public bool Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceActivityType {
        
        /// <remarks/>
        Arrive,
        
        /// <remarks/>
        Depart,
        
        /// <remarks/>
        ArriveDepart,
        
        /// <remarks/>
        Unavailable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceStopInformation {
        
        private DepartureBoardServiceCallingStopStatus callingStopStatusField;
        
        private DepartureBoardServiceInformation departureField;
        
        private DepartureBoardServiceInformation[] previousIntermediatesField;
        
        private DepartureBoardServiceInformation stopField;
        
        private DepartureBoardServiceInformation[] onwardIntermediatesField;
        
        private DepartureBoardServiceInformation arrivalField;
        
        private DepartureBoardServiceItinerary serviceField;
        
        private DepartureBoardServiceType modeField;
        
        private bool circularRouteField;
        
        private string falseDestinationField;
        
        private string viaField;
        
        private bool cancelledField;
        
        private string cancellationReasonField;
        
        private string lateReasonField;
        
        private bool hasTrainDetailsField;
        
        /// <remarks/>
        public DepartureBoardServiceCallingStopStatus CallingStopStatus {
            get {
                return this.callingStopStatusField;
            }
            set {
                this.callingStopStatusField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceInformation Departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceInformation[] PreviousIntermediates {
            get {
                return this.previousIntermediatesField;
            }
            set {
                this.previousIntermediatesField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceInformation Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceInformation[] OnwardIntermediates {
            get {
                return this.onwardIntermediatesField;
            }
            set {
                this.onwardIntermediatesField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceInformation Arrival {
            get {
                return this.arrivalField;
            }
            set {
                this.arrivalField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceItinerary Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public DepartureBoardServiceType Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public bool CircularRoute {
            get {
                return this.circularRouteField;
            }
            set {
                this.circularRouteField = value;
            }
        }
        
        /// <remarks/>
        public string FalseDestination {
            get {
                return this.falseDestinationField;
            }
            set {
                this.falseDestinationField = value;
            }
        }
        
        /// <remarks/>
        public string Via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
        
        /// <remarks/>
        public bool Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        public string CancellationReason {
            get {
                return this.cancellationReasonField;
            }
            set {
                this.cancellationReasonField = value;
            }
        }
        
        /// <remarks/>
        public string LateReason {
            get {
                return this.lateReasonField;
            }
            set {
                this.lateReasonField = value;
            }
        }
        
        /// <remarks/>
        public bool HasTrainDetails {
            get {
                return this.hasTrainDetailsField;
            }
            set {
                this.hasTrainDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceCallingStopStatus {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        HasCallingStops,
        
        /// <remarks/>
        NoCallingStops,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceType {
        
        /// <remarks/>
        Train,
        
        /// <remarks/>
        BusCoach,
        
        /// <remarks/>
        Flight,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public partial class DepartureBoardServiceTimeRequest {
        
        private DepartureBoardServiceTimeRequestType typeField;
        
        private int hourField;
        
        private int minuteField;
        
        /// <remarks/>
        public DepartureBoardServiceTimeRequestType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        public int Minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceTimeRequestType {
        
        /// <remarks/>
        Now,
        
        /// <remarks/>
        Last,
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        TimeToday,
        
        /// <remarks/>
        TimeTomorrow,
        
        /// <remarks/>
        LastToday,
        
        /// <remarks/>
        LastTomorrow,
        
        /// <remarks/>
        FirstToday,
        
        /// <remarks/>
        FirstTomorrow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.transportdirect.info/TransportDirect.EnhancedExposedServices.Departure" +
        "Board.V1")]
    public enum DepartureBoardServiceRangeType {
        
        /// <remarks/>
        Sequence,
        
        /// <remarks/>
        Interval,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDepartureBoardCompletedEventHandler(object sender, GetDepartureBoardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartureBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartureBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartureBoardServiceStopInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartureBoardServiceStopInformation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDepartureBoardTimeRequestTypesCompletedEventHandler(object sender, GetDepartureBoardTimeRequestTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartureBoardTimeRequestTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartureBoardTimeRequestTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartureBoardServiceTimeRequestType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartureBoardServiceTimeRequestType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591